Style:
  Enabled: false
Metrics:
  Enabled: false
Naming:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Layout/MultilineBlockLayout:
  Exclude:
    - spec/**/*.rb

Layout/BlockEndNewline:
  Exclude:
    - spec/**/*.rb
